"""create user profiles table

Revision ID: 25ea7d200c9a
Revises: 5873b2467b03
Create Date: 2026-08-11 19:45:24.257365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ea7d200c9a'
down_revision: Union[str, Sequence[str], None] = '5873b2467b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('preferred_min_price', sa.Float(), nullable=False),
    sa.Column('preferred_max_price', sa.Float(), nullable=False),
    sa.Column('preferred_categories', sa.String(length=500), nullable=False),
    sa.Column('preferred_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
